### ISSUE TITLE
libvlccore这个工程中连接依赖

### ISSUE THREAD

**Issue by bigbao9494** [niozhao/vlc-3.0.11-VS2019#2]
在libvlccore这个工程中连接依赖：
libcompat.lib
Ws2_32.lib
Iphlpapi.lib
Normaliz.lib
Synchronization.lib
libiconv.a
libintl.a
libgcc.a
libgcrypt.a
libgpg-error.a
legacy_stdio_definitions.lib
libmingwex.a

编译的时候提示找不到libiconv.a，实际工程中也没有libiconv.a这个文件，还有其它的.a文件也没有

**Comment by niozhao** [comment]
抱歉才看到邮件。
你没有仔细看readme.txt 吧。
1：stdalign.h  是win sdk中文件，需要升级你的win10 sdk
2：这些lib，都在vlc-3.0.11-VS2019\libs\x64\libs_part_1.rar    libs_part_2.rar 里，需要先解压。


readme里有说明。
















在 2021-04-22 17:37:33，"bigbao9494" ***@***.***> 写道：

在libvlccore这个工程中连接依赖：
libcompat.lib
Ws2_32.lib
Iphlpapi.lib
Normaliz.lib
Synchronization.lib
libiconv.a
libintl.a
libgcc.a
libgcrypt.a
libgpg-error.a
legacy_stdio_definitions.lib
libmingwex.a

编译的时候提示找不到libiconv.a，实际工程中也没有libiconv.a这个文件，还有其它的.a文件也没有
