### ISSUE TITLE
编译错误问题，后续

### ISSUE THREAD

**Issue by bigbao9494** [niozhao/vlc-3.0.11-VS2019#3]
抱歉才看到邮件。
你没有仔细看readme.txt 吧。
1：stdalign.h  是win sdk中文件，需要升级你的win10 sdk
2：这些lib，都在vlc-3.0.11-VS2019\libs\x64\libs_part_1.rar    libs_part_2.rar 里，需要先解压。
readme里有说明。

其实我有看readme
2:  Download the "Insider Preview Windows 10 SDK" and install to support C11/C17 feature. (now Windows SDK Version is 10.0.20206.0, reference https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/ )

我的VS2019是10天前下载的，下载VS2019时会包含SDK，我在项目“属性”-->“SDK版本”里面看到的是2项：10.0(最新安装的版本)、10.0.19041.0
你是说一定需要10.0.20206.0版本的SDK才行？我上面的那个版本是不行的？10.0(最新安装的版本)--这个不知道是不是最新的、
10.0.19041.0--这个感觉很接近了

libs_part_1.rar和libs_part_2.rar的问题确实是我只解压了libs_part_1，我以为是一个压缩包分成了2个卷，所以
解压了libs_part_1后就以为全部完成了，就没有去解压libs_part_2

另外再问一下：
	vlc-3.0.11-VS2019-master和vlc-3.0.11-VS2019-vlc-3.0.11-change分支有什么区别？
	我看你好像最近只更新了vlc-3.0.11-VS2019-vlc-3.0.11-change分支

**Comment by niozhao** [comment]
你的win10 sdk 最好升级一下，我不确定10.0.19041.0是否OK。 vlc-3.0.11-change是我自己的一些修改，大家有可能不需要。
